//
// Copyright (C) 2015 crosire & kagikn & contributors
// License: https://github.com/scripthookvdotnet/scripthookvdotnet#license
//

using System;

namespace GTA
{
    [Obsolete("The v2 API is deprecated, use the v3 API instead.")]
    public enum ExplosionType
    {
        Grenade,
        GrenadeL,
        StickyBomb,
        Molotov1,
        Rocket,
        TankShell,
        HiOctane,
        Car,
        Plane,
        PetrolPump,
        Bike,
        Steam,
        Flame,
        WaterHydrant,
        GasCanister,
        Boat,
        ShipDestroy,
        Truck,
        Bullet,
        SmokeGL,
        SmokeG,
        BZGas,
        Flare,
        GasCanister2,
        Extinguisher,
        ProgramAR,
        Train,
        Barrel,
        Propane,
        Blimp,
        FlameExplode,
        Tanker,
        PlaneRocket,
        VehicleBullet,
        GasTank,
        BirdCrap,
        Railgun,
        Blimp2,
        FireWork,
        SnowBall,
        ProxMine,
        Valkyrie,
        AirDefense,
        PipeBomb,
        VehicleMine,
        ExplosiveAmmo,
        ApcShell,
        BombCluster,
        BombGas,
        BombIncendiary,
        BombStandard,
        Torpedo,
        TorpedoUnderwater,
        BombushkaCannon,
        BombClusterSecondary,
        HunterBarrage,
        HunterCannon,
        RogueCannon,
        MineUnderwater,
        OrbitalCannon,
        BombStandardWide,
        ExplosiveAmmoShotgun,
        Oppressor2Cannon,
        MortarKinetic,
        VehiclemineKinetic,
        VehiclemineEmp,
        VehiclemineSpike,
        VehiclemineSlick,
        VehiclemineTar,
        ScriptDrone,
        RayGun,
        BuriedMine,
        ScriptMissile,
        RCTankRocket,
        BombWater,
        BombWaterSecondary,
        ScriptMissileLarge = 81,
        SubmarineBig,
        EmpLauncherEmp,
        RailgunXm3,
        BalancedCannons,
    }
}
